x=10
try:
    print(x)
except:
    print('not gona work')
finally:
    print("it's done")#The finally block, if specified, will be executed regardless if the try block raises an error or not.